#!/bin/bash
#This script assumes you have installed geoip and it's databases.
#If you have not please install geoiplookup
if [ $# -eq 0 ]
   then
     echo "No arguments supplied, need ip or file containing line seperated ips"
     exit
fi

FILENAME=$1
if [ -e $FILENAME ]; then
   while read line
      do
#         num=`shuf -i 1-7 -n 1`
#         echo "$(tput setaf $num)Checking for $line"
         echo "Checking for $line"
         geoiplookup $line
         curl ipinfo.io/$line
         echo -e "\n"
#         echo -e "\n$(tput sgr0)"
      done < $FILENAME
else
   geoiplookup $1
   curl ipinfo.io/$1
fi
