#!/bin/bash
#bash script to replay tty logs from kippo. It also 
#colorizes them for easy viewing
if [ $# -eq 0 ]
    then
	echo "No arguments supplied give path to dir containing logs"
	exit
fi


for file in $1/*.log
do
	num=`shuf -i 1-7 -n 1`
	if [ -z "$numold" ]
	then
		echo ""
	else 
		while [ $num = $numold ]
		do
			num=`shuf -i 1-7 -n 1`
		done
	fi
	echo  "$(tput setaf $num)$file"
	../utils/playlog.py $file
	echo -e "\n$(tput sgr0)"
	numold=$num
done
